language: cpp
dist: trusty
sudo: required
cache:
  - apt
python:
  - "2.7"
  - "3.4"
install:
  - env
  - make update
  - make buildso
# command to run tests
script:
  - make venv-autobuild-tests
# package dependencies
before_install:
  #- env
  #- sudo -E env
  - sudo apt-get update -y -qq
  - sudo -E make venv-deps
