language: cpp

sudo: required

env:
  matrix:
    - DOCKER_BASE=ubuntu:latest
    - DOCKER_BASE=debian:latest

services:
  - docker

before_install:
  - docker pull ${DOCKER_BASE}
  - docker build --build-arg DOCKER_BASE=${DOCKER_BASE} .
  
script:
  - make venv-dev-autobuild-tests
  - make venv-pypi-autobuild-tests
  - make venv-pypilive-autobuild-tests
