language: python
cache:
  - apt
  - directories:
    - $HOME/.pip-cache/
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
#  - env
  - make pip
# command to run tests
script:
  - make update
  - make build
  - make install
# package dependencies
before_install:
#  - env
  - sudo apt-get update -y -qq
  - sudo make deps
